AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Strava MCP Server - Remote MCP running on AWS Lambda (Free Tier Compatible)

  A Model Context Protocol server for the Strava API that runs serverless on AWS Lambda.
  Designed to stay within AWS Free Tier limits for personal portfolio use.

Globals:
  Function:
    Timeout: 900  # 15 minutes (max for Lambda Function URLs) - needed for long SSE connections
    MemorySize: 512  # MB (Free tier allows up to 3.2M seconds of 512MB compute)
    Runtime: nodejs20.x
    Architectures:
      - arm64  # Graviton2 - cheaper and faster
    Environment:
      Variables:
        NODE_ENV: production

Parameters:
  StravaClientId:
    Type: String
    Description: Strava API Client ID
    NoEcho: false

  StravaClientSecret:
    Type: String
    Description: Strava API Client Secret
    NoEcho: true

  StravaRefreshToken:
    Type: String
    Description: Strava API Refresh Token
    NoEcho: true

  AuthToken:
    Type: String
    Description: Bearer token for authenticating MCP client requests (use a long random string)
    NoEcho: true
    Default: ""
    AllowedPattern: '^$|.{32,}$'

  SecretsManagerArn:
    Type: String
    Description: Optional Secrets Manager ARN containing Strava credentials (JSON payload)
    Default: ""

  OAuthEnabled:
    Type: String
    Description: Enable OAuth 2.1 endpoints for Claude Web connectors
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

  OAuthAllowedRedirectUris:
    Type: String
    Description: Comma-separated list of allowed OAuth redirect URIs
    Default: "https://claude.ai/api/mcp/auth_callback,https://claude.com/api/mcp/auth_callback,https://chatgpt.com/connector_platform_oauth_redirect"

  OAuthRegistrationToken:
    Type: String
    Description: Optional bearer token to protect dynamic client registration
    Default: ""

Conditions:
  HasSecretsManagerArn: !Not [!Equals [!Ref SecretsManagerArn, ""]]

Resources:
  StravaMCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: strava-mcp-server
      Description: Strava MCP Server with Streamable HTTP transport
      CodeUri: dist/
      Handler: run.sh
      Environment:
        Variables:
          STRAVA_CLIENT_ID: !Ref StravaClientId
          STRAVA_CLIENT_SECRET: !Ref StravaClientSecret
          STRAVA_REFRESH_TOKEN: !Ref StravaRefreshToken
          AUTH_TOKEN: !Ref AuthToken
          SECRETS_MANAGER_ARN: !Ref SecretsManagerArn
          OAUTH_ENABLED: !Ref OAuthEnabled
          OAUTH_CLIENTS_TABLE: !Ref OAuthClientsTable
          OAUTH_CODES_TABLE: !Ref OAuthAuthCodesTable
          OAUTH_TOKENS_TABLE: !Ref OAuthTokensTable
          OAUTH_ALLOWED_REDIRECT_URIS: !Ref OAuthAllowedRedirectUris
          OAUTH_REGISTRATION_TOKEN: !Ref OAuthRegistrationToken
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          AWS_LWA_PORT: 8080
          AWS_LWA_READINESS_CHECK_PATH: /health
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerArm64:25
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OAuthClientsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OAuthAuthCodesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OAuthTokensTable
        - !If
          - HasSecretsManagerArn
          - Statement:
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref SecretsManagerArn
          - !Ref AWS::NoValue
      FunctionUrlConfig:
        AuthType: NONE  # Public URL with Bearer token authentication in application code
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
          AllowHeaders:
            - Content-Type
            - Authorization
            - Accept
            - X-Requested-With
          AllowCredentials: false
          MaxAge: 86400
        InvokeMode: RESPONSE_STREAM  # Enable streaming for SSE support
      Tags:
        Project: StravaMCP
        Environment: Production
        CostCenter: FreeTier

  OAuthClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: strava-mcp-oauth-clients
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
      KeySchema:
        - AttributeName: client_id
          KeyType: HASH

  OAuthAuthCodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: strava-mcp-oauth-codes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  OAuthTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: strava-mcp-oauth-tokens
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: access_token
          AttributeType: S
        - AttributeName: refresh_token
          AttributeType: S
      KeySchema:
        - AttributeName: access_token
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: refresh_token_index
          KeySchema:
            - AttributeName: refresh_token
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

Outputs:
  StravaMCPUrl:
    Description: "Function URL for Strava MCP Server"
    Value: !GetAtt StravaMCPFunctionUrl.FunctionUrl

  StravaMCPFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt StravaMCPFunction.Arn

  ClaudeConnectionUrl:
    Description: "Base URL to use for Claude MCP connector"
    Value: !GetAtt StravaMCPFunctionUrl.FunctionUrl

  HealthCheckUrl:
    Description: "Health check endpoint"
    Value: !Sub "${StravaMCPFunctionUrl.FunctionUrl}health"
